### ISSUE TITLE
Could not show the dependencies with customized States

### ISSUE THREAD

**Issue by pkrdax** [ALM-Rangers/Show-Area-Path-Dependencies#12]
Hi,
This is very helpful for us to track dependencies between user stories,
but we still have some issues.

We use customized template to create our team project, and there are some different states from default user story template, like "**Ready for Dev**", "**In Dev**":
![image](https://cloud.githubusercontent.com/assets/25037094/25367278/43cc48a2-29a7-11e7-98fe-d8293cd71005.png)

After we test the extension, it seems to be fine with specific state, but we don't know why it doesn't work for all cases, here are some test cases for you:

1. Both of stories in "**New**", shows stories relation correctly.
![image](https://cloud.githubusercontent.com/assets/25037094/25368473/4f850f46-29af-11e7-922e-9acb3e2a8a30.png)

2. One story in "**New**" and another in "**Ready for Dev**", only shows relation of us2.
![image](https://cloud.githubusercontent.com/assets/25037094/25368314/305c9ac2-29ae-11e7-9364-63cc97f101a8.png)

3. Both of stories in "**Ready for Dev**", it just keep finding and we had been waiting for it over 10 mins.
![image](https://cloud.githubusercontent.com/assets/25037094/25368598/142c08fe-29b0-11e7-91db-c931357c04c5.png)

Could you confirm the issues? or any suggestion will be helpful,

thanks.

**Comment by NielZeeman** [comment]
At the time of writing the extension there was no way to dynamically get the list of states using the client API. We currently just get the standard states of "New", "Approved", "Committed", and "Active".

An item is on the backlog to change it to rather query based on items that is **not** closed or resolved.

**Comment by pkrdax** [comment]
Thank you,
what would be the timeline for this item on your backlog? :)

**Comment by jeffrey-opdam** [comment]
Closing issues, as the project is deprecated
