### ISSUE TITLE
Update link to license in the Marketplace?

### ISSUE THREAD

**Issue by NinoCapo** [ALM-Rangers/Show-Area-Path-Dependencies#16]
Will the the license referenced in the marketplace be updated to match the license update in the repo?

**Comment by wpschaub** [comment]
The license on the marketplace is different as the repo (code) is owner by the ALM | DevOps Ranger community, and the extension is hosted by Microsoft, on behalf of the community.

**Comment by NinoCapo** [comment]
Would that mean that every extension in the marketplace falls under the Microsoft Software License?  Trying to make sure I have everything covered from an enterprise legal perspective.

**Comment by wpschaub** [comment]
No, every extension points to its license. In our case the license for Rangers extensions hosted under DevLabs is the same, but differs from others.

**Comment by NinoCapo** [comment]
Thank you, that makes sense now.
